### ISSUE TITLE
paragraphs

### ISSUE THREAD

**Issue by LDubya** [2Associes/meteor-boilerplate#42]
Where are paragraphs set at?

I see that it's a mongo collection, but where are they initialized in the code?

a recursive grep of the root for words like "veniam" returns nothing.

**Comment by marsimeau** [comment]
There are 2 places where Paragraphs gets touched.

In [paragrahs.js](https://github.com/2Associes/meteor-boilerplate/blob/master/imports/api/paragraphs/paragraphs.js), where it is initialized:
`const Paragraphs = new TAPi18n.Collection('paragraphs', { base_language: 'fr-CA' })`

Then in the [fixtures.js](https://github.com/2Associes/meteor-boilerplate/blob/master/imports/startup/server/fixtures.js), dummy paragraphs are inserted.

The collection is initialized using the [tap:i18n-db](https://github.com/TAPevents/tap-i18n-db) package. This allows translation in collection documents.

**Comment by LDubya** [comment]
ah I figured you were using a random text generator.

Is this explained somewhere in the docs? I don't mind reading if I know where to look

**Comment by marsimeau** [comment]
@LDubya 

If you are asking about the features of Faker.js, it has its own documentation [here](http://marak.github.io/faker.js/). Otherwise, I will let the issue open so @huguesbrunelle can determine if it is worth being added to our docs.

**Comment by LDubya** [comment]
Yeah, I didn't even know you were using faker and finding out about it took a lot of digging. Even just saying that paragraphs are created using faker.js on the fixtures.js file is fine.

**Comment by huguesbrunelle** [comment]
Hey @LDubya I just made a few changes to the README. Hope it helps.
